### ISSUE TITLE
throws exceptions. urgent

### ISSUE THREAD

**Issue by consigliory** [stormpath/stormpath-aspnetcore#27] opened 2016-10-11 09:12 UTC
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Could not parse account status value 'UNKNOWN'
System.Exception: Could not parse account status value 'UNKNOWN'
   at Stormpath.SDK.Account.AccountStatus.Parse(String status)
   at Stormpath.SDK.Impl.Serialization.FieldConverters.StatusFieldConverters.AccountStatusConverter.ConvertImpl(KeyValuePair`2 token)
   at Stormpath.SDK.Impl.Serialization.FieldConverters.AbstractFieldConverter.TryConvertField(KeyValuePair`2 token, Type targetType)
   at Stormpath.SDK.Impl.Serialization.FieldConverters.FieldConverterList.TryConvertField(KeyValuePair`2 token, Type targetType)
   at Stormpath.SDK.Impl.Serialization.JsonSerializationProvider.ConvertProperties(IDictionary`2 properties, Type targetType)
   at Stormpath.SDK.Impl.DataStore.DefaultDataStore.GetBody[T](IHttpResponse response)
   at Stormpath.SDK.Impl.DataStore.DefaultDataStore.<>c__DisplayClass78_0`1.<<GetResourceDataAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.SDK.Impl.DataStore.Filters.AccountStoreMappingCacheInvalidationFilter.<Stormpath-SDK-Impl-DataStore-Filters-IAsynchronousFilter-FilterAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.SDK.Impl.DataStore.Filters.ProviderAccountResultFilter.<Stormpath-SDK-Impl-DataStore-Filters-IAsynchronousFilter-FilterAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.SDK.Impl.DataStore.Filters.WriteCacheFilter.<FilterAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.SDK.Impl.DataStore.Filters.ReadCacheFilter.<FilterAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.SDK.Impl.DataStore.DefaultDataStore.<Stormpath-SDK-DataStore-IDataStore-GetResourceAsync>d__68`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.Owin.Middleware.Route.LoginRoute.<HandleLogin>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.Owin.Middleware.Route.LoginRoute.<PostHtmlAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.Owin.Middleware.Route.AbstractRoute.<InvokeAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Stormpath.Owin.Middleware.Route.AbstractRoute.<InvokeAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stormpath.Owin.Middleware.StormpathMiddleware.<Invoke>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Owin.WebSocketAcceptAdapter.<>c__DisplayClass6_0.<<AdaptWebSockets>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

**Comment by consigliory** [comment] 2016-10-11 09:16
this is urgent. login does not work

**Comment by hristiyan-dimov** [comment] 2016-10-11 11:36
This issue is blocking customer demos and production environments at the moment for us as well. 

What is the reason for this and when there will be fix for this?

Status: blocking/highest priority!

**Comment by nbarbettini** [comment] 2016-10-11 11:43
Looking at this now. Feel free to join [Talk Stormpath Slack](https://talkstormpath.shipit.xyz/) for updates. I will also update here.

**Comment by serge-sedelnikov** [comment] 2016-10-11 13:07
Confirm, still not working, failed with the same issue, SDK for .NET is not fetching the profile. OAuth Token endpoint works fine.

I applied hot fix for my production but still waiting it to be fixed from your side

Status: blocking/highest priority!

**Comment by nbarbettini** [comment] 2016-10-11 13:21
Fixed and pushed out as [Stormpath.SDK 0.94.2](https://www.nuget.org/packages/Stormpath.SDK/0.94.2). NuGet should index the package within a few minutes.

Let me know if you still have problems after applying the updated package.

**Comment by nbarbettini** [comment] 2016-10-11 13:21
Also, I've identified the root cause and will take steps to ensure it doesn't happen again. 👍  Sorry for the frustration y'all!

**Comment by consigliory** [comment] 2016-10-11 13:23
In our project we use directly stormpath.aspnetcore 0.6.0.

**Comment by nbarbettini** [comment] 2016-10-11 13:26
If you install the updated Stormpath.SDK version, it will work with the
existing AspNetCore package.

Let me know if you need assistance.

**Comment by serge-sedelnikov** [comment] 2016-10-11 14:04
I will also check it in 2 hours from home

**Comment by nbarbettini** [comment] 2016-10-11 14:50
Update: No longer necessary to install `Stormpath.SDK` separately, you can just update `Stormpath.AspNetCore` to the latest release (0.6.1).

**Comment by nbarbettini** [comment] 2016-10-11 14:50
@consigliory Once you've had a chance to test and verify that you are no longer blocked, can you close?

**Comment by consigliory** [comment] 2016-10-11 14:51
Sure. Thanks for quick response

**Comment by nbarbettini** [comment] 2016-10-11 14:52
Of course. Sorry for the unexpected inconvenience. Ping me here or on Talk Stormpath Slack if you have any further questions!

**Comment by serge-sedelnikov** [comment] 2016-10-11 15:18
Thanks!!
T.
Sergey
11 окт. 2016 г. 5:50 PM пользователь Nate Barbettini <notifications@github.com> написал:Update: No longer necessary to install Stormpath.SDK separately, you can just update Stormpath.AspNetCore to the latest release (0.6.1).

**Closed** 2016-10-11 20:59 UTC
Labels: bug
